name: localmusicapp
description: A local music app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^12.0.4
  sqflite: ^2.2.2
  get: ^4.6.5
  audioplayers: ^1.1.1
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/


